# Generated by Django 4.0.1 on 2022-06-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_userlog_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
