# Generated by Django 4.0.1 on 2022-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_userlog_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='user',
        ),
        migrations.AddField(
            model_name='userlog',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
