# Generated by Django 4.0.1 on 2022-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_remove_userlog_user_userlog_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='logout_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
