# Generated by Django 4.0.1 on 2022-06-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_alter_userlog_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='login_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='logout_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
